/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f9f9f9",
        "error-container": "#fe8983",
        "primary-fixed": "#d9e3f9",
        "on-secondary-fixed": "#3a4044",
        "background": "#f9f9f9",
        "secondary-fixed-dim": "#d0d5da",
        "on-surface": "#2d3435",
        "primary": "#555f71",
        "outline": "#757c7d",
        "surface-container": "#ebeeef",
        "primary-container": "#d9e3f9",
        "on-primary-fixed": "#364051",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#001222",
        "on-primary": "#f6f7ff",
        "inverse-surface": "#0c0f0f",
        "secondary-fixed": "#dee3e8",
        "on-primary-container": "#485264",
        "on-error": "#fff7f6",
        "outline-variant": "#acb3b4",
        "surface-variant": "#dde4e5",
        "on-secondary": "#f4f9fe",
        "secondary-container": "#dee3e8",
        "on-tertiary-container": "#002e4e",
        "tertiary-dim": "#00578b",
        "surface-container-low": "#f2f4f4",
        "on-error-container": "#752121",
        "secondary-dim": "#4e5458",
        "on-surface-variant": "#596061",
        "primary-dim": "#495365",
        "inverse-primary": "#dee8ff",
        "on-background": "#2d3435",
        "surface-tint": "#555f71",
        "inverse-on-surface": "#9c9d9d",
        "tertiary-fixed-dim": "#4fa3ec",
        "surface-container-high": "#e4e9ea",
        "tertiary": "#00639e",
        "tertiary-container": "#5eb1fb",
        "on-tertiary-fixed-variant": "#00385c",
        "primary-fixed-dim": "#cbd5eb",
        "surface-dim": "#d3dbdd",
        "tertiary-fixed": "#5eb1fb",
        "error-dim": "#4e0309",
        "error": "#9f403d",
        "on-secondary-fixed-variant": "#575c60",
        "surface": "#f9f9f9",
        "on-primary-fixed-variant": "#525c6e",
        "surface-container-highest": "#dde4e5",
        "secondary": "#5a6064",
        "on-tertiary": "#f7f9ff",
        "on-secondary-container": "#4d5257"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"],
        "display": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
