site_name: Nievo EasyFin Docs
site_url: https://nievo.com.br/easy-fin/docs

nav:
  - Home: index.md
  - Arquitetura do Sistema:
    - Visão Geral: content/ArquiteturaSistema/intro.md
    - Banco de Dados e Esquemas: content/ArquiteturaSistema/banco_de_dados.md
    - Gateway e Infraestrutura: content/ArquiteturaSistema/infraestrutura.md
  - Fluxos de Negócio:
    - Visão Geral: content/FluxosNegocio/intro.md
    - Sobre e Casos de Uso: content/FluxosNegocio/about.md
    - Onboarding e Aceite de Termos: content/FluxosNegocio/onboarding_termos.md
    - Autenticação e Segurança: content/FluxosNegocio/autenticacao_seguranca.md
    - Gestão de Contas e Cartões: content/FluxosNegocio/gestao_contas_cartoes.md
  - Frontend:
    - Arquitetura e Componentes: content/Frontend/intro.md
  - APIs e Integrações:
    - Visão Geral e Kong Gateway: content/ApiIntegracoes/intro.md
    - Endpoints de Autenticação (Auth): content/ApiIntegracoes/auth_endpoints.md
    - Endpoints de Contas e Cartões (Core): content/ApiIntegracoes/core_endpoints.md
  - Procedimentos Operacionais:
    - Ambiente e Desenvolvimento: content/ProcedimentosOperacionais/intro.md
    - Docker, Clusters e Migrações: content/ProcedimentosOperacionais/docker_migracoes.md
  - Boas Práticas:
    - Padrões Técnicos e Arquitetura: content/BoasPraticas/intro.md
  - Atualizações e Histórico:
    - Histórico de Alterações (Changelog): content/AtualizacoesHistorico/intro.md

theme:
  name: material
  logo: images/nievo-logo-arredondado.png
  favicon: images/favicon.ico
  palette:
    - scheme: slate       # modo escuro
      primary: '#0092d1'  # azul mais moderno e agradável
      accent: '#ff8800'   # laranja suave e visível
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default     # modo claro
      primary: '#0077b6'  # azul consistente, mais limpo no branco
      accent: '#ff7f00'   # mantém identidade
      toggle:
        icon: material/white-balance-sunny
        name: Switch to dark mode
  font:
    text: Roboto
    code: Fira Code
  features:
    - navigation.expand
    - navigation.top
    - navigation.tabs
    - search.suggest
    - content.code.copy
extra_css:
  - styles/custom.css
