services:
  mkdoc:
    image: squidfunk/mkdocs-material:9
    restart: always
    container_name: nievo-easy-fin-docs
    hostname: nievo-easy-fin.docs.com
    volumes:
      - ./config/:/docs
    networks:
      - docs
    ports:
      - "6030:8000"

networks:
  docs:
    driver: bridge
